package golden

import (
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// canonicalDDL is the CREATE TABLE for analytics.orders exactly as the
// specification prints it (docs/Iris Specification Inventory.md section 5).
// The checked-in golden testdata/orders_create.sql must equal these bytes;
// E03's real DDL generator will be asserted against the same golden.
const canonicalDDL = `CREATE TABLE analytics.orders (
    id          uuid        PRIMARY KEY,
    customer_id uuid        NOT NULL,
    amount      numeric,
    created_at  timestamptz DEFAULT now()
);
`

// canonicalAlter is the --dry-run migration preview from section 5, verbatim.
const canonicalAlter = `ALTER TABLE analytics.orders ADD COLUMN status text DEFAULT 'pending';
`

// TestGoldenByteDiff proves that a generated artifact is compared byte-for-byte
// against a checked-in golden file and that any difference fails the test.
//
// spec: S16/golden-byte-diff
func TestGoldenByteDiff(t *testing.T) {
	cases := []struct {
		name   string
		got    []byte
		golden string
	}{
		{"ddl", []byte(canonicalDDL), filepath.Join("testdata", "orders_create.sql")},
		{"dry-run-alter", []byte(canonicalAlter), filepath.Join("testdata", "add_status.alter.sql")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// Byte-identical artifact passes.
			if err := check(tc.got, tc.golden, false); err != nil {
				t.Fatalf("byte-identical artifact rejected: %v", err)
			}
			// The exported wrapper passes on a match with a real *testing.T.
			Assert(t, tc.got, tc.golden)

			// Any difference fails: one byte changed, added, or removed.
			mutations := map[string][]byte{
				"one byte changed": flipFirst(tc.got),
				"one byte added":   append(append([]byte{}, tc.got...), 'X'),
				"one byte removed": tc.got[:len(tc.got)-1],
			}
			for name, mutated := range mutations {
				if err := check(mutated, tc.golden, false); err == nil {
					t.Errorf("%s: mutated artifact accepted, want a diff failure", name)
				}
			}
		})
	}

	// A missing golden is a failure, never a silent pass.
	if err := check([]byte("x"), filepath.Join("testdata", "does_not_exist.golden"), false); err == nil {
		t.Error("missing golden accepted, want failure")
	}
}

// TestGoldenUpdateFlag proves that the -update flag regenerates golden files in
// place instead of failing on a diff. The behavior is exercised against a
// throwaway temp golden so a normal `go test` run never rewrites a checked-in
// golden, and the flag is restored before the test returns.
//
// spec: S16/golden-update-flag
func TestGoldenUpdateFlag(t *testing.T) {
	// The -update flag is registered on the package's flag set.
	if flag.Lookup("update") == nil {
		t.Fatal("-update flag not registered on the package flag set")
	}

	dir := t.TempDir()
	goldenPath := filepath.Join(dir, "sub", "artifact.golden")
	payload := []byte("first generated bytes\n")

	// No golden yet: a normal compare fails.
	if err := check(payload, goldenPath, false); err == nil {
		t.Fatal("compare against an absent golden accepted, want failure")
	}
	// -update creates it in place (including parent dirs), no failure.
	if err := check(payload, goldenPath, true); err != nil {
		t.Fatalf("update against an absent golden failed: %v", err)
	}
	onDisk, err := os.ReadFile(goldenPath) //nolint:gosec // G304: goldenPath is a fixed filename under this test's own t.TempDir(); no external input.
	if err != nil {
		t.Fatalf("golden not written by -update: %v", err)
	}
	if string(onDisk) != string(payload) {
		t.Fatalf("written golden = %q, want %q", onDisk, payload)
	}
	// Now a normal compare passes.
	if err := check(payload, goldenPath, false); err != nil {
		t.Fatalf("compare after -update failed: %v", err)
	}

	// Regenerate in place: a changed artifact fails the compare, -update
	// overwrites the golden, and the compare then passes.
	changed := []byte("second generated bytes\n")
	if err := check(changed, goldenPath, false); err == nil {
		t.Fatal("changed artifact matched a stale golden, want a diff failure")
	}
	if err := check(changed, goldenPath, true); err != nil {
		t.Fatalf("update-in-place failed: %v", err)
	}
	if err := check(changed, goldenPath, false); err != nil {
		t.Fatalf("compare after update-in-place failed: %v", err)
	}

	// The exported Assert honors the real flag against a temp copy; restore
	// the flag afterwards so no checked-in golden is ever rewritten.
	saved := *update
	defer func() { *update = saved }()
	*update = true
	tempGolden := filepath.Join(dir, "via-flag.golden")
	Assert(t, []byte("via flag\n"), tempGolden) // creates it, does not fail
	*update = false
	Assert(t, []byte("via flag\n"), tempGolden) // now matches
}

// flipFirst returns a copy of b with its first byte inverted.
func flipFirst(b []byte) []byte {
	out := append([]byte{}, b...)
	if len(out) > 0 {
		out[0] ^= 0xff
	}
	return out
}
